### ISSUE TITLE
ReactOS Application ManagerからReactOS-JPN-Packageのダウンロードに失敗する

### ISSUE THREAD

**Issue by hangingman** [katahiromz/ReactOS-JPN-Package#3]
下記スクリーンショットに記載の環境でインストールを試みたのですが、ダウンロードに失敗します。
他のパッケージのインストールには成功するのでネットワークの疎通が原因ではないように見えます。
ReactOSは以下のコミットハッシュのものをビルドしました。
https://github.com/reactos/reactos/commit/ce65553eaa0506962064f8f2224b149ad45d6bdb

![reactos](https://user-images.githubusercontent.com/1238507/127332462-f4778e4e-672d-4f29-a870-cea8e76dd4aa.png)

**Comment by katahiromz** [comment]
既知の問題かと思います。
https://jira.reactos.org/browse/CORE-16741
GitHub が新しい暗号化方式を使っていてReactOSでは対応できてないのが原因です。

**Comment by hangingman** [comment]
@katahiromz ありがとうございます、これはわかりませんね…
ちなみにApplication Managerを使わずFirefox等からDLしてインストールすることはできました

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/commit/e0a47b7b5ffc7d8dd5b883875200b56cec8ef923

再テストお願いします。

**Comment by hangingman** [comment]
@katahiromz 

手元の環境でreactosをビルドして試してみました

```shell
(RosBE) hiroyuki:~/git/reactos (master=) $ git log --oneline | head
a4bd2449adc [MSPAINT] Follow-up of #4237
```

この状態でビルドしたのでGitのハッシュは https://github.com/reactos/reactos/commit/a4bd2449adc9d129bf6ccb3dcfc4b9c06149f708 だと思います。e0a47b7は入っているはず。
ReactOS-JPN-Packageは無事アプリケーションマネージャーからインストールできました :tada: 
ReactOS詳しくないので、とりあえず以上です。すごい！

![package1](https://user-images.githubusercontent.com/1238507/148228459-e433dabe-a964-4a4d-a6d8-88dcf08801a1.png)
![package2](https://user-images.githubusercontent.com/1238507/148228472-238bbc38-5541-46d5-8b02-4eb1c078ee80.png)

**Comment by katahiromz** [comment]
Fixed.
